services:
  - type: web
    name: legal-clarity
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: HF_HOME
        value: /tmp/huggingface_cache 
    ports:
      - 5003